# SWE-agent Base Configuration for YudaiV3 AI Solver
# This configuration defines the default settings for running SWE-agent

agent:
  model:
    model_name: "openrouter/anthropic/claude-3.5-sonnet"
    temperature: 0.1
    max_tokens: 4000
    top_p: 0.9
    api_base: "https://openrouter.ai/api/v1"
  
  # Agent behavior settings
  max_iterations: 50
  max_time_seconds: 1800  # 30 minutes
  max_cost: 10.0  # $10 max per solve session
  
  # Tool configuration
  tools:
    - str_replace_editor
    - bash
    - python
    - search_files
    - find_files
    - edit_file
    - create_file
    - view_file

environment:
  # Docker environment settings
  image: "sweagent/swe-agent:latest"
  data_path: "/data/swe_runs"
  repo_path: "/tmp/repo"
  
  # Environment variables
  env_vars:
    PYTHONPATH: "/tmp/repo"
    PYTHONUNBUFFERED: "1"
    
  # Resource limits
  memory_limit: "2g"
  cpu_limit: "2"
  timeout: 1800

# Command configuration
commands:
  install: "pip install -e ."
  test: "python -m pytest"
  lint: "flake8 ."
  format: "black ."

# Logging configuration
logging:
  level: "INFO"
  trajectory_path: "/data/swe_runs/trajectories"
  log_file: "/data/swe_runs/solver.log"
  
  # What to log
  log_trajectory: true
  log_commands: true
  log_outputs: true
  log_errors: true

# Safety and limits
safety:
  # Prevent dangerous operations
  forbidden_commands:
    - "rm -rf /"
    - "sudo"
    - "chmod 777"
    - "dd if="
  
  # File operation limits
  max_file_size: 1048576  # 1MB
  max_files_per_operation: 100
  
  # Network restrictions
  allow_network: false
  allowed_domains: []

# Solver-specific settings
solver:
  # How to approach problems
  strategy: "systematic"  # systematic, exploratory, focused
  
  # Code analysis preferences
  prefer_existing_patterns: true
  maintain_code_style: true
  add_documentation: true
  add_tests: false  # Disabled for faster solving
  
  # Git integration
  create_commits: false  # We handle this in the adapter
  commit_message_template: "AI Solver: {action} - {file_path}"

# Issue processing
issue_processing:
  # How to parse and understand issues
  extract_requirements: true
  identify_files: true
  analyze_dependencies: true
  
  # Response format
  provide_summary: true
  explain_changes: true
  suggest_testing: true

# Performance tuning
performance:
  # Caching
  cache_file_contents: true
  cache_analysis_results: true
  
  # Parallel processing
  parallel_file_analysis: false  # Keep simple for now
  max_parallel_tasks: 1
  
  # Memory management
  clear_cache_after_iterations: 10
  max_memory_usage: "1g"