version: '3.8'

services:
  # PostgreSQL Database
  db:
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    container_name: yudai_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=yudai_db
      - POSTGRES_USER=yudai_user
      - POSTGRES_PASSWORD=yudai_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - yudai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yudai_user -d yudai_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yudai_backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://yudai_user:yudai_password@db:5432/yudai_db
      - DB_ECHO=false
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - yudai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Frontend React Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yudai_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - yudai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

# Volumes
volumes:
  postgres_data:
    driver: local

# Networks  
networks:
  yudai-network:
    driver: bridge 