import React, { useState, useCallback, useMemo } from 'react';
import { Send, Plus } from 'lucide-react';
import { Message } from '../types';
import type {
  ChatContextMessage,
  FileContextItem,
  CreateIssueWithContextRequest,
  GitHubIssuePreview,
  UserIssueResponse,
  ChatAction
} from '../types/sessionTypes';
import { useQueryClient } from '@tanstack/react-query';
import {
  useChatMessages,
  useContextCards,
  useFileDependencies,
  useAddContextCard,
  useCreateIssueWithContext,
  useCreateGitHubIssueFromUserIssue
} from '../hooks/useSessionQueries';
import { useSessionManagement } from '../hooks/useSessionManagement';
import { useRepository } from '../hooks/useRepository';
import { useSessionStore } from '../stores/sessionStore';
import { API, buildApiUrl } from '../config/api';

// Types are now imported from '../types'

// Define missing types
interface ChatProps {
  onShowError?: (message: string) => void;
}

interface IssuePreviewModalProps {
  issuePreview: IssuePreviewData;
  onClose: () => void;
  onCreateIssue: () => void;
  onRegenerateIssue: () => void;
  onSolveIssue: (issueId: string) => void;
  isCreating: boolean;
}

// Define IssuePreviewData interface that extends GitHubIssuePreview
interface IssuePreviewData extends GitHubIssuePreview {
  userIssue?: UserIssueResponse;
  conversationContext: ChatContextMessage[];
  fileContext: FileContextItem[];
  canCreateGitHubIssue: boolean;
  repositoryInfo?: {
    owner: string;
    name: string;
    branch?: string;
  };
}

const IssuePreviewModal: React.FC<IssuePreviewModalProps> = ({
  issuePreview,
  onClose,
  onCreateIssue,
  onRegenerateIssue,
  onSolveIssue,
  isCreating
}) => {
  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-bg-secondary border border-border rounded-xl shadow-terminal max-w-4xl w-full max-h-[90vh] overflow-y-auto animate-fade-in">
        <div className="p-6 border-b border-border">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-mono font-semibold text-fg">GitHub Issue Preview</h2>
            <button
              onClick={onClose}
              className="text-muted hover:text-fg text-2xl transition-colors"
            >
              &times;
            </button>
          </div>
        </div>

        <div className="p-6 space-y-6">
          {/* Issue Title */}
          <div>
            <label className="block text-xs font-mono uppercase tracking-wider text-muted mb-2">Title</label>
            <div className="bg-bg-tertiary border border-border rounded-lg p-3 text-fg font-mono">{issuePreview.title}</div>
          </div>

          {/* Issue Body */}
          <div>
            <label className="block text-xs font-mono uppercase tracking-wider text-muted mb-2">Description</label>
            <div className="bg-bg-tertiary border border-border rounded-lg p-3 text-fg whitespace-pre-wrap max-h-96 overflow-y-auto font-mono text-sm">
              {issuePreview.body}
            </div>
          </div>

          {/* Labels */}
          <div>
            <label className="block text-xs font-mono uppercase tracking-wider text-muted mb-2">Labels</label>
            <div className="flex flex-wrap gap-2">
              {issuePreview.labels?.map((label, index) => (
                <span
                  key={index}
                  className="bg-cyan/10 text-cyan border border-cyan/20 px-3 py-1 rounded-full text-xs font-mono"
                >
                  {label}
                </span>
              ))}
            </div>
          </div>

          {/* Repository Info */}
          <div>
            <label className="block text-xs font-mono uppercase tracking-wider text-muted mb-2">Repository</label>
            <div className="bg-bg-tertiary border border-border rounded-lg p-3 text-fg-secondary font-mono text-sm">
              {issuePreview.repositoryInfo?.owner}/{issuePreview.repositoryInfo?.name}
              {issuePreview.repositoryInfo?.branch && ` (${issuePreview.repositoryInfo.branch})`}
            </div>
          </div>

          {/* Metadata */}
          <div>
            <label className="block text-xs font-mono uppercase tracking-wider text-muted mb-2">Metadata</label>
            <div className="bg-bg-tertiary border border-border rounded-lg p-3 text-muted text-xs font-mono space-y-1">
              <div>Generated by LLM: {issuePreview.metadata?.generated_by_llm ? 'Yes' : 'No'}</div>
              <div>Messages Count: {issuePreview.metadata?.chat_messages_count || 'N/A'}</div>
              <div>Files Count: {issuePreview.metadata?.files_context_count || 'N/A'}</div>
              <div>Tokens Used: {issuePreview.metadata?.total_tokens || issuePreview.metadata?.tokens_used || 'N/A'}</div>
              <div>LLM Model: {issuePreview.metadata?.llm_model || 'x-ai/grok-4-fast'}</div>
              <div>Generation Method: {issuePreview.metadata?.generation_method || 'llm'}</div>
              {issuePreview.metadata?.processing_time && (
                <div>Processing Time: {issuePreview.metadata.processing_time.toFixed(2)}s</div>
              )}
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="p-6 border-t border-border flex gap-3 justify-end">
          <button
            onClick={onRegenerateIssue}
            disabled={isCreating}
            className="px-4 py-2.5 bg-bg-tertiary hover:bg-border/50 disabled:opacity-50 text-fg rounded-lg font-mono text-sm transition-all duration-200 disabled:cursor-not-allowed border border-border"
          >
            Regenerate Issue
          </button>
          <button
            onClick={onCreateIssue}
            disabled={isCreating}
            className="px-4 py-2.5 bg-success hover:bg-success/90 disabled:opacity-50 text-bg-primary rounded-lg font-mono text-sm font-semibold transition-all duration-200 disabled:cursor-not-allowed flex items-center gap-2 glow-emerald"
          >
            {isCreating && <div className="animate-spin rounded-full h-4 w-4 border-2 border-bg-primary/20 border-t-bg-primary" />}
            {isCreating ? 'Creating...' : 'Create GitHub Issue'}
          </button>
          <button
            onClick={() => {
              // Handle solve issue functionality
              if (issuePreview.userIssue?.issue_id) {
                onSolveIssue(issuePreview.userIssue.issue_id);
              }
            }}
            disabled={isCreating}
            className="px-4 py-2.5 bg-cyan hover:bg-cyan/90 disabled:opacity-50 text-bg-primary rounded-lg font-mono text-sm font-semibold transition-all duration-200 disabled:cursor-not-allowed flex items-center gap-2 glow-cyan"
          >
            <div className="animate-spin rounded-full h-4 w-4 border-2 border-bg-primary/20 border-t-bg-primary" />
            Solve Issue
          </button>
        </div>
      </div>
    </div>
  );
};

const BUTTON_ACTION_REGEX = /Button\{\s*"([^"]+)"\s*\}/gi;

const extractSuggestedTaskTitles = (content: string): string[] => {
  const lines = content.split('\n').map(line => line.trim());
  const titles: string[] = [];
  lines.forEach((line, index) => {
    if (line.toLowerCase().startsWith('suggested task')) {
      const nextLine = lines.slice(index + 1).find(candidate => candidate.length > 0);
      if (nextLine) {
        titles.push(nextLine);
      }
    }
  });
  return titles;
};

const extractButtonActions = (content: string): ChatAction[] => {
  BUTTON_ACTION_REGEX.lastIndex = 0;
  const matches = [...content.matchAll(BUTTON_ACTION_REGEX)];
  if (!matches.length) {
    return [];
  }
  const suggestedTitles = extractSuggestedTaskTitles(content);
  return matches.map((match, index) => {
    const label = match[1].trim();
    const issueTitle = suggestedTitles[index];
    const combined = `${label} ${issueTitle || ''}`.toLowerCase();
    const labels: string[] = [];
    if (combined.includes('bug')) {
      labels.push('bug');
    }
    if (combined.includes('enhancement')) {
      labels.push('enhancement');
    }
    if (!labels.length && combined.includes('task')) {
      labels.push('task');
    }
    return {
      action_type: 'create_issue',
      label,
      issue_title: issueTitle,
      labels,
    };
  });
};

const stripButtonActions = (content: string): string => {
  BUTTON_ACTION_REGEX.lastIndex = 0;
  return content.replace(BUTTON_ACTION_REGEX, '').trim();
};

const shouldShowDefaultActions = (content: string): boolean => {
  return /suggested task/i.test(content) || /suggested tasks/i.test(content);
};

const defaultIssueActions: ChatAction[] = [
  { action_type: 'create_issue', label: 'Start Task' },
  { action_type: 'create_issue', label: 'Create bug issue', labels: ['bug'] },
  { action_type: 'create_issue', label: 'Create enhancement issue', labels: ['enhancement'] },
];

// ChatWithPreview component removed - functionality integrated into main Chat component

export const Chat: React.FC<ChatProps> = ({
  onShowError
}) => {
  // Session management hook for state management
  const { activeSessionId } = useSessionManagement();
  const { selectedRepository } = useRepository();

  const queryClient = useQueryClient();
  const { sendChatMessage } = useSessionStore();

  // State for issue preview modal
  const [showIssuePreview, setShowIssuePreview] = useState(false);
  const [currentIssuePreview, setCurrentIssuePreview] = useState<IssuePreviewData | null>(null);

  // Use the correct hooks from useSessionQueries
  const { data: chatMessages = [] } = useChatMessages(activeSessionId || '');
  const { data: contextCards = [] } = useContextCards(activeSessionId || '');
  const { data: fileContext = [] } = useFileDependencies(activeSessionId || '');

  // Convert API messages to Message format for display
  const messages: Message[] = chatMessages.map((msg) => ({
    id: msg.message_id,
    content: msg.message_text,
    timestamp: new Date(msg.created_at),
    sessionId: activeSessionId || 'default',
    role: msg.role || 'user',
    actions: msg.actions,
  }));

  // Simplified messages state without session management
  const [input, setInput] = useState('');
  const [hoveredMessage, setHoveredMessage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isCreatingIssue, setIsCreatingIssue] = useState(false);
  // Extraction deprecated; indexing happens automatically.

  // Count user messages (messages that are not the initial system messages)
  const userMessageCount = messages.filter(msg =>
    msg.id !== '1' && msg.id !== '2'
  ).length;

  // Get relevant files based on current conversation context
  const relevantFiles = useMemo(() => {
    if (!fileContext || fileContext.length === 0) return [];

    // Simple relevance scoring based on file type and recent messages
    const recentMessages = messages.slice(-3); // Last 3 messages
    const messageText = recentMessages.map(m => m.content).join(' ').toLowerCase();

    return fileContext
      .filter((file) => {
        // Prioritize files that might be relevant to the conversation
        const fileName = (file.name || file.file_name || '').toLowerCase();
        const filePath = (file.path || file.file_path || '').toLowerCase();

        // Check if file name or path contains keywords from recent messages
        const keywords = messageText.split(' ').filter(word => word.length > 3);
        return keywords.some(keyword =>
          fileName.includes(keyword) || filePath.includes(keyword)
        );
      })
      .slice(0, 3); // Show top 3 relevant files
  }, [fileContext, messages]);

  const showError = useCallback((message: string) => {
    console.error('[Chat] Error occurred:', message);
    if (onShowError) {
      onShowError(message);
    } else {
      console.error('Chat Error:', message);
    }
  }, [onShowError]);

  // Session creation is now handled by useSessionManagement hook
  // This component no longer needs to create sessions directly

  const addContextCardMutation = useAddContextCard();
  const createIssueMutation = useCreateIssueWithContext();
  const createGitHubIssueMutation = useCreateGitHubIssueFromUserIssue();

  const handleAddToContext = useCallback(async (content: string) => {
    if (!activeSessionId) {
      showError('No active session to add context to');
      return;
    }

    addContextCardMutation.mutate({
      sessionId: activeSessionId,
      card: {
        title: 'Chat Message',
        description: content.length > 100 ? content.substring(0, 100) + '...' : content,
        source: 'chat',
        tokens: Math.ceil(content.length / 4),
        content,
      },
    }, {
      onError: () => showError('Failed to add to context'),
    });
  }, [activeSessionId, addContextCardMutation, showError]);

  const handleSend = useCallback(async () => {
      if (!input.trim() || isLoading || !activeSessionId) {
          return;
      }

      const currentInput = input;
      setInput('');
      setIsLoading(true);

      try {
          // Use unified sessionStore method for sending chat messages
          const response = await sendChatMessage(
              currentInput,
              contextCards.map((card) => card.id),
              selectedRepository || undefined
          );

          if (response) {
              console.log('[Chat] Message sent successfully:', response.message_id);

              // Invalidate and refetch the messages to show the updated conversation
              await queryClient.invalidateQueries({
                queryKey: ['messages', activeSessionId]
              });
          }

      } catch (error) {
          console.error('[Chat] Message sending failed:', error);
          showError('Failed to send message. Please try again.');
      } finally {
          setIsLoading(false);
      }
  }, [input, isLoading, activeSessionId, contextCards, selectedRepository, sendChatMessage, showError, queryClient]);

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleCreateGitHubIssue = useCallback(async (action?: ChatAction) => {
    if (isCreatingIssue || !selectedRepository) {
      return;
    }

    setIsCreatingIssue(true);

    try {
      // Filter out system messages and convert to ChatContextMessage format
      const conversationMessages: ChatContextMessage[] = messages
        .filter(msg => msg.id !== '1' && msg.id !== '2')
        .map(msg => ({
          id: msg.id,
          content: msg.content,
          isCode: false, // Default to false for chat messages
          timestamp: msg.timestamp.toISOString()
        }));

      console.log('[Chat] Prepared conversation messages:', conversationMessages);

      // Convert file context to FileContextItem format
      const fileContextItems: FileContextItem[] = fileContext.map((file) => ({
        id: file.id,
        name: file.name || file.file_name || '',
        type: file.type || 'INTERNAL',
        tokens: file.tokens,
        category: file.category || '',
        path: file.path || file.file_path || ''
      }));

      // Prepare the request using the proper API method
      const fallbackTitle = `Issue from Chat Session - ${selectedRepository.repository.name}`;
      const descriptionParts = [
        action?.issue_description,
        action?.labels && action.labels.length > 0 ? `Suggested labels: ${action.labels.join(', ')}` : null
      ].filter(Boolean) as string[];
      const requestDescription = descriptionParts.length > 0
        ? descriptionParts.join('\n\n')
        : 'This issue was generated from a chat conversation with file dependency context.';

      const request: CreateIssueWithContextRequest = {
        title: action?.issue_title || fallbackTitle,
        description: requestDescription,
        chat_messages: conversationMessages,
        file_context: fileContextItems,
        repository_info: {
          owner: selectedRepository.repository.full_name.split('/')[0],
          name: selectedRepository.repository.full_name.split('/')[1],
          branch: selectedRepository.branch
        },
        priority: 'medium'
      };

      // Use the unified sessionStore method for creating issues with context
      const response = await createIssueMutation.mutateAsync(request);

      if (response && response.success) {
        const issuePreview: IssuePreviewData = {
          ...response.github_preview,
          userIssue: response.user_issue as UserIssueResponse,
          conversationContext: conversationMessages,
          fileContext: fileContextItems,
          canCreateGitHubIssue: true,
          repositoryInfo: request.repository_info
        };

        // Show the preview modal
        setCurrentIssuePreview(issuePreview);
        setShowIssuePreview(true);
      }

    } catch (error) {
      console.error('[Chat] Issue creation failed:', error);
      const errorText = `Failed to create GitHub issue: ${error instanceof Error ? error.message : 'Unknown error'}`;
      showError(errorText);
    } finally {
      setIsCreatingIssue(false);
    }
  }, [isCreatingIssue, selectedRepository, messages, fileContext, showError, createIssueMutation]);

  const handleConfirmCreateIssue = useCallback(async () => {
    if (!currentIssuePreview || !currentIssuePreview.userIssue) {
      return;
    }

    try {
      // Call the create GitHub issue API with proper parameters
      if (currentIssuePreview.userIssue?.issue_id) {
        const result = await createGitHubIssueMutation.mutateAsync(currentIssuePreview.userIssue.issue_id);

        if (result?.success && result?.github_url) {
          console.log('[Chat] GitHub issue created successfully:', result.github_url);
          setShowIssuePreview(false);
          setCurrentIssuePreview(null);
          showError(`✓ GitHub issue created successfully! ${result.github_url}`);
        } else {
          showError(result?.message || 'Failed to create GitHub issue');
        }
      }
    } catch (error) {
      console.error('[Chat] Failed to create GitHub issue:', error);
      showError(`Failed to create GitHub issue: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [currentIssuePreview, showError, createGitHubIssueMutation]);

  const handleRegenerateIssue = useCallback(async () => {
    // Close the preview and regenerate
    setShowIssuePreview(false);
    setCurrentIssuePreview(null);
    // Trigger the create issue process again
    await handleCreateGitHubIssue();
  }, [handleCreateGitHubIssue]);

  const handleSolveIssue = useCallback(async (issueId: string) => {
    if (!selectedRepository || !currentIssuePreview) {
      showError('No repository or issue selected for solving');
      return;
    }

    try {
      console.log('[Chat] Starting solver for issue:', issueId);

      // Close the preview modal
      setShowIssuePreview(false);
      setCurrentIssuePreview(null);

      // Call the solver endpoint using unified API
      const response = await fetch(buildApiUrl(API.SESSIONS.SOLVER.START, { sessionId: activeSessionId || '' }), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('session_token') || ''}`,
        },
        body: JSON.stringify({
          issue_id: issueId,
          repo_url: `https://github.com/${selectedRepository.repository.full_name}`,
          branch_name: selectedRepository.branch || 'main',
        }),
      });

      if (!response.ok) {
        throw new Error(`Solver request failed: ${response.statusText}`);
      }

      const result = await response.json();
      console.log('[Chat] Solver started successfully:', result);

      // Invalidate messages to show solver status updates
      await queryClient.invalidateQueries({
        queryKey: ['messages', activeSessionId]
      });

      // Show success message
      showError(`🚀 AI Solver started! Session ID: ${result.solve_session_id}. Watch the chat for progress updates.`);

    } catch (error) {
      console.error('[Chat] Failed to start solver:', error);
      showError(`Failed to start solver: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [selectedRepository, activeSessionId, currentIssuePreview, showError, queryClient]);



  return (
    <div className="h-full flex flex-col bg-bg terminal-noise">
      {/* Session Status Indicator */}
      {!selectedRepository && (
        <div className="bg-amber/10 border border-amber/30 rounded-lg p-4 m-4 animate-fade-in">
          <div className="flex items-center gap-2 mb-2">
            <span className="w-2 h-2 rounded-full bg-amber animate-pulse" style={{ boxShadow: '0 0 8px rgba(245, 158, 11, 0.5)' }} />
            <span className="text-amber font-mono font-medium text-sm">No Active Repository</span>
          </div>
          <p className="text-amber/80 text-sm mb-3 font-mono">
            Please select a repository to start a new session and begin chatting with Daifu.
          </p>
          <button
            onClick={() => {
              // Trigger repository selection manually
              window.location.reload();
            }}
            className="bg-amber hover:bg-amber/90 text-bg-primary px-4 py-2 rounded-lg text-sm font-mono font-semibold transition-all duration-200 glow-amber"
          >
            Select Repository
          </button>
        </div>
      )}

      {/* File Context Display */}
      {relevantFiles.length > 0 && (
        <div className="bg-bg-secondary border border-border rounded-lg p-3 mx-4 mb-4 animate-fade-in">
          <div className="flex items-center gap-2 text-xs font-mono text-muted mb-2">
            <span className="w-1.5 h-1.5 rounded-full bg-cyan" />
            <span className="uppercase tracking-wider">Relevant Files</span>
          </div>
          <div className="space-y-1">
            {relevantFiles.map((file) => (
              <div key={file.id} className="flex items-center justify-between text-xs group">
                <span className="text-fg-secondary truncate flex-1 font-mono">
                  {file.name || file.file_name}
                </span>
                <div className="flex items-center gap-2">
                  <span className="text-muted font-mono">{file.tokens} tokens</span>
                  <button
                    onClick={() => handleAddToContext(`File: ${file.name || file.file_name} (${file.path || file.file_path})`)}
                    className="text-cyan hover:text-cyan/80 text-xs font-mono opacity-0 group-hover:opacity-100 transition-opacity"
                    title="Add file to context"
                  >
                    Add
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Messages Container */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((message, index) => {
          const parsedActions = extractButtonActions(message.content);
          const cleanedContent = stripButtonActions(message.content);
          const messageActions = message.actions && message.actions.length > 0
            ? message.actions
            : parsedActions;
          const actionsToRender = message.role === 'assistant' && messageActions.length === 0 && shouldShowDefaultActions(cleanedContent)
            ? defaultIssueActions
            : messageActions;

          return (
          <div
            key={message.id}
            className={`flex ${message.role === 'assistant' ? 'justify-start' : 'justify-end'} animate-fade-in`}
            style={{ animationDelay: `${index * 50}ms` }}
            onMouseEnter={() => setHoveredMessage(message.id)}
            onMouseLeave={() => setHoveredMessage(null)}
          >
            <div
              className={`max-w-[70%] rounded-xl p-4 transition-all duration-200 ${
                message.role === 'assistant'
                  ? 'bg-bg-secondary border border-border text-fg hover:border-border-accent'
                  : 'bg-amber/10 border border-amber/30 text-fg'
              }`}
            >
              <div className="whitespace-pre-wrap font-mono text-sm leading-relaxed">{cleanedContent}</div>
              {message.role === 'assistant' && actionsToRender.length > 0 && (
                <div className="mt-3 pt-3 border-t border-border/50 flex flex-wrap gap-2">
                  {actionsToRender.map((action, actionIndex) => (
                    <button
                      key={`${message.id}-${actionIndex}`}
                      onClick={() => handleCreateGitHubIssue(action)}
                      disabled={isCreatingIssue || !selectedRepository}
                      className="text-xs font-mono bg-bg-tertiary hover:bg-border/50 px-3 py-1.5 rounded-lg text-fg-secondary hover:text-fg transition-all duration-200 border border-border disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {action.label}
                    </button>
                  ))}
                </div>
              )}
              {hoveredMessage === message.id && message.id !== '1' && message.id !== '2' && (
                <div className="mt-3 pt-3 border-t border-border/50">
                  <button
                    onClick={() => handleAddToContext(cleanedContent)}
                    className="text-xs font-mono bg-bg-tertiary hover:bg-border/50 px-3 py-1.5 rounded-lg text-muted hover:text-fg transition-all duration-200 border border-border"
                  >
                    + Add to Context
                  </button>
                </div>
              )}
            </div>
          </div>
          );
        })}

        {isLoading && (
          <div className="flex justify-start animate-fade-in">
            <div className="bg-bg-secondary border border-border text-fg rounded-xl p-4">
              <div className="flex items-center gap-3">
                <div className="flex gap-1">
                  <span className="w-2 h-2 rounded-full bg-amber animate-pulse" style={{ animationDelay: '0ms' }} />
                  <span className="w-2 h-2 rounded-full bg-amber animate-pulse" style={{ animationDelay: '150ms' }} />
                  <span className="w-2 h-2 rounded-full bg-amber animate-pulse" style={{ animationDelay: '300ms' }} />
                </div>
                <span className="font-mono text-sm text-muted">Daifu is thinking...</span>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Input Area */}
      <div className="border-t border-border p-4 bg-bg-secondary">
        <div className="flex gap-3">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder={selectedRepository ? "Type your message..." : "Select a repository to start chatting..."}
            disabled={!selectedRepository || isLoading}
            className="flex-1 bg-bg-tertiary border border-border rounded-lg px-4 py-3 text-fg placeholder:text-muted font-mono text-sm focus:outline-none focus:border-amber/50 focus:ring-2 focus:ring-amber/10 disabled:opacity-50 transition-all duration-200"
          />
          <button
            onClick={handleSend}
            disabled={!input.trim() || isLoading || !selectedRepository}
            className="bg-amber hover:bg-amber/90 disabled:bg-bg-tertiary disabled:border-border disabled:cursor-not-allowed text-bg-primary disabled:text-muted px-5 py-3 rounded-lg flex items-center gap-2 font-mono text-sm font-semibold transition-all duration-200 border border-amber disabled:border-border glow-amber disabled:shadow-none"
          >
            {isLoading ? (
              <div className="animate-spin rounded-full h-4 w-4 border-2 border-bg-primary/20 border-t-bg-primary" />
            ) : (
              <Send size={16} />
            )}
            {isLoading ? 'Sending' : 'Send'}
          </button>
          <button
            onClick={handleCreateGitHubIssue}
            disabled={isCreatingIssue || userMessageCount < 1 || !selectedRepository}
            className="bg-success hover:bg-success/90 disabled:bg-bg-tertiary disabled:border-border disabled:cursor-not-allowed text-bg-primary disabled:text-muted px-5 py-3 rounded-lg flex items-center gap-2 font-mono text-sm font-semibold transition-all duration-200 border border-success disabled:border-border glow-emerald disabled:shadow-none"
            title={!selectedRepository ? 'Select a repository first' : userMessageCount < 1 ? 'Send at least one message' : 'Create GitHub issue from conversation'}
          >
            {isCreatingIssue ? (
              <div className="animate-spin rounded-full h-4 w-4 border-2 border-bg-primary/20 border-t-bg-primary" />
            ) : (
              <Plus size={16} />
            )}
            {isCreatingIssue ? 'Creating' : 'Create Issue'}
          </button>
        </div>
      </div>

      {/* Issue Preview Modal */}
      {showIssuePreview && currentIssuePreview && (
        <IssuePreviewModal
          issuePreview={currentIssuePreview}
          onClose={() => {
            setShowIssuePreview(false);
            setCurrentIssuePreview(null);
          }}
          onCreateIssue={handleConfirmCreateIssue}
          onRegenerateIssue={handleRegenerateIssue}
          onSolveIssue={handleSolveIssue}
          isCreating={isCreatingIssue}
        />
      )}
    </div>
  );
};

// Duplicate IssuePreviewModal component removed - using the one defined at the top
