import React, { useState, useCallback } from 'react';
import { Send, Plus } from 'lucide-react';
import { useShallow } from 'zustand/react/shallow';
import { Message } from '../types';
import type {
  ChatContextMessage,
  CreateIssueWithContextRequest,
  GitHubIssuePreview,
  UserIssueResponse,
  ChatAction
} from '../types/sessionTypes';
import { useRepository } from '../hooks/useRepository';
import { useSessionStore } from '../stores/sessionStore';
import { useAuthStore } from '../stores/authStore';
import { API, buildApiUrl } from '../config/api';
import { buildExecutionObjective } from '../utils/workflowObjective';

// Types are now imported from '../types'

// Define missing types
interface ChatProps {
  onShowError?: (message: string) => void;
}

interface IssuePreviewModalProps {
  issuePreview: IssuePreviewData;
  onClose: () => void;
  onCreateIssue: () => void;
  onRegenerateIssue: () => void;
  onSolveIssue: (issueId: string) => void;
  isCreating: boolean;
}

// Define IssuePreviewData interface that extends GitHubIssuePreview
interface IssuePreviewData extends GitHubIssuePreview {
  userIssue?: UserIssueResponse;
  conversationContext: ChatContextMessage[];
  canCreateGitHubIssue: boolean;
  repositoryInfo?: {
    owner: string;
    name: string;
    branch?: string;
  };
}

const IssuePreviewModal: React.FC<IssuePreviewModalProps> = ({
  issuePreview,
  onClose,
  onCreateIssue,
  onRegenerateIssue,
  onSolveIssue,
  isCreating
}) => {
  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-bg-secondary border border-border rounded-xl shadow-terminal max-w-4xl w-full max-h-[90vh] overflow-y-auto animate-fade-in">
        <div className="p-6 border-b border-border">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-mono font-semibold text-fg">GitHub Issue Preview</h2>
            <button
              onClick={onClose}
              className="text-muted hover:text-fg text-2xl transition-colors"
            >
              &times;
            </button>
          </div>
        </div>

        <div className="p-6 space-y-6">
          {/* Issue Title */}
          <div>
            <p className="block text-xs font-mono uppercase tracking-wider text-muted mb-2">Title</p>
            <div className="bg-bg-tertiary border border-border rounded-lg p-3 text-fg font-mono">{issuePreview.title}</div>
          </div>

          {/* Issue Body */}
          <div>
            <p className="block text-xs font-mono uppercase tracking-wider text-muted mb-2">Description</p>
            <div className="bg-bg-tertiary border border-border rounded-lg p-3 text-fg whitespace-pre-wrap max-h-96 overflow-y-auto font-mono text-sm">
              {issuePreview.body}
            </div>
          </div>

          {/* Labels */}
          <div>
            <p className="block text-xs font-mono uppercase tracking-wider text-muted mb-2">Labels</p>
            <div className="flex flex-wrap gap-2">
              {issuePreview.labels?.map((label) => (
                <span
                  key={`${issuePreview.title}-${label}`}
                  className="bg-cyan/10 text-cyan border border-cyan/20 px-3 py-1 rounded-full text-xs font-mono"
                >
                  {label}
                </span>
              ))}
            </div>
          </div>

          {/* Repository Info */}
          <div>
            <p className="block text-xs font-mono uppercase tracking-wider text-muted mb-2">Repository</p>
            <div className="bg-bg-tertiary border border-border rounded-lg p-3 text-fg-secondary font-mono text-sm">
              {issuePreview.repositoryInfo?.owner}/{issuePreview.repositoryInfo?.name}
              {issuePreview.repositoryInfo?.branch && ` (${issuePreview.repositoryInfo.branch})`}
            </div>
          </div>

          {/* Metadata */}
          <div>
            <p className="block text-xs font-mono uppercase tracking-wider text-muted mb-2">Metadata</p>
            <div className="bg-bg-tertiary border border-border rounded-lg p-3 text-muted text-xs font-mono space-y-1">
              <div>Generated by LLM: {issuePreview.metadata?.generated_by_llm ? 'Yes' : 'No'}</div>
              <div>Messages Count: {issuePreview.metadata?.chat_messages_count || 'N/A'}</div>
              <div>Tokens Used: {issuePreview.metadata?.total_tokens || issuePreview.metadata?.tokens_used || 'N/A'}</div>
              <div>LLM Model: {issuePreview.metadata?.llm_model || 'x-ai/grok-4-fast'}</div>
              <div>Generation Method: {issuePreview.metadata?.generation_method || 'llm'}</div>
              {issuePreview.metadata?.processing_time && (
                <div>Processing Time: {issuePreview.metadata.processing_time.toFixed(2)}s</div>
              )}
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="p-6 border-t border-border flex gap-3 justify-end">
          <button
            onClick={onRegenerateIssue}
            disabled={isCreating}
            className="px-4 py-2.5 bg-bg-tertiary hover:bg-border/50 disabled:opacity-50 text-fg rounded-lg font-mono text-sm transition-all duration-200 disabled:cursor-not-allowed border border-border"
          >
            Regenerate Issue
          </button>
          <button
            onClick={onCreateIssue}
            disabled={isCreating}
            className="px-4 py-2.5 bg-success hover:bg-success/90 disabled:opacity-50 text-bg-primary rounded-lg font-mono text-sm font-semibold transition-all duration-200 disabled:cursor-not-allowed flex items-center gap-2 glow-emerald"
          >
            {isCreating && <div className="animate-spin rounded-full h-4 w-4 border-2 border-bg-primary/20 border-t-bg-primary" />}
            {isCreating ? 'Creating...' : 'Create GitHub Issue'}
          </button>
          <button
            onClick={() => {
              // Handle solve issue functionality
              if (issuePreview.userIssue?.issue_id) {
                onSolveIssue(issuePreview.userIssue.issue_id);
              }
            }}
            disabled={isCreating}
            className="px-4 py-2.5 bg-cyan hover:bg-cyan/90 disabled:opacity-50 text-bg-primary rounded-lg font-mono text-sm font-semibold transition-all duration-200 disabled:cursor-not-allowed flex items-center gap-2 glow-cyan"
          >
            <div className="animate-spin rounded-full h-4 w-4 border-2 border-bg-primary/20 border-t-bg-primary" />
            Solve Issue
          </button>
        </div>
      </div>
    </div>
  );
};

const BUTTON_ACTION_REGEX = /Button\{\s*"([^"]+)"\s*\}/gi;

const extractSuggestedTaskTitles = (content: string): string[] => {
  const lines = content.split('\n').map(line => line.trim());
  const titles: string[] = [];
  lines.forEach((line, index) => {
    if (line.toLowerCase().startsWith('suggested task')) {
      const nextLine = lines.slice(index + 1).find(candidate => candidate.length > 0);
      if (nextLine) {
        titles.push(nextLine);
      }
    }
  });
  return titles;
};

const extractButtonActions = (content: string): ChatAction[] => {
  BUTTON_ACTION_REGEX.lastIndex = 0;
  const matches = [...content.matchAll(BUTTON_ACTION_REGEX)];
  if (!matches.length) {
    return [];
  }
  const suggestedTitles = extractSuggestedTaskTitles(content);
  return matches.map((match, index) => {
    const label = match[1].trim();
    const issueTitle = suggestedTitles[index];
    const combined = `${label} ${issueTitle || ''}`.toLowerCase();
    const labels: string[] = [];
    if (combined.includes('bug')) {
      labels.push('bug');
    }
    if (combined.includes('enhancement')) {
      labels.push('enhancement');
    }
    if (!labels.length && combined.includes('task')) {
      labels.push('task');
    }
    return {
      action_type: 'create_issue',
      label,
      issue_title: issueTitle,
      labels,
    };
  });
};

const stripButtonActions = (content: string): string => {
  BUTTON_ACTION_REGEX.lastIndex = 0;
  return content.replace(BUTTON_ACTION_REGEX, '').trim();
};

const shouldShowDefaultActions = (content: string): boolean => {
  return /suggested task/i.test(content) || /suggested tasks/i.test(content);
};

const defaultIssueActions: ChatAction[] = [
  { action_type: 'create_issue', label: 'Start Task' },
  { action_type: 'create_issue', label: 'Create bug issue', labels: ['bug'] },
  { action_type: 'create_issue', label: 'Create enhancement issue', labels: ['enhancement'] },
];

// ChatWithPreview component removed - functionality integrated into main Chat component

export const Chat: React.FC<ChatProps> = ({
  onShowError
}) => {
  const { selectedRepository } = useRepository();
  const sessionToken = useAuthStore((state) => state.sessionToken);
  const {
    activeSessionId,
    sessionStatus,
    error: sessionError,
    messages: chatMessages,
    contextCards,
    isLoadingMessages,
    messageError,
    runtimeStatus,
    isExploringCodebase,
    explorationDetail,
    sendChatMessage,
    createContextCard,
    createIssueWithContext,
    createGitHubIssueFromUserIssue,
    loadMessages,
    setRuntimeState,
    syncRuntimeState,
    setActiveTab,
  } = useSessionStore(
    useShallow((state) => ({
      activeSessionId: state.activeSessionId,
      sessionStatus: state.sessionStatus,
      error: state.error,
      messages: state.messages,
      contextCards: state.contextCards,
      isLoadingMessages: state.isLoadingMessages,
      messageError: state.messageError,
      runtimeStatus: state.runtimeStatus,
      isExploringCodebase: state.isExploringCodebase,
      explorationDetail: state.explorationDetail,
      sendChatMessage: state.sendChatMessage,
      createContextCard: state.createContextCard,
      createIssueWithContext: state.createIssueWithContext,
      createGitHubIssueFromUserIssue: state.createGitHubIssueFromUserIssue,
      loadMessages: state.loadMessages,
      setRuntimeState: state.setRuntimeState,
      syncRuntimeState: state.syncRuntimeState,
      setActiveTab: state.setActiveTab,
    }))
  );

  // State for issue preview modal
  const [issuePreviewModal, setIssuePreviewModal] = useState<{
    isOpen: boolean;
    data: IssuePreviewData | null;
  }>({
    isOpen: false,
    data: null,
  });

  // Convert API messages to Message format for display
  const messages: Message[] = chatMessages.map((msg) => ({
    id: msg.message_id,
    content: msg.message_text,
    timestamp: new Date(msg.created_at),
    sessionId: activeSessionId || 'default',
    role: msg.role || 'user',
    actions: msg.actions,
  }));

  // Simplified messages state without session management
  const [input, setInput] = useState('');
  const [hoveredMessage, setHoveredMessage] = useState<string | null>(null);
  const [isCreatingIssue, setIsCreatingIssue] = useState(false);
  const isSending = isLoadingMessages || sessionStatus === 'sending';
  const isSessionReady = sessionStatus === 'ready' && !!activeSessionId;

  // Count user messages (messages that are not the initial system messages)
  const userMessageCount = messages.filter(msg =>
    msg.id !== '1' && msg.id !== '2'
  ).length;

  const showError = useCallback((message: string) => {
    console.error('[Chat] Error occurred:', message);
    if (onShowError) {
      onShowError(message);
    } else {
      console.error('Chat Error:', message);
    }
  }, [onShowError]);

  const handleAddToContext = useCallback(async (content: string) => {
    if (!activeSessionId) {
      showError('No active session to add context to');
      return;
    }

    try {
      await createContextCard({
        title: 'Chat Message',
        description: content.length > 100 ? `${content.substring(0, 100)}...` : content,
        source: 'chat',
        tokens: Math.ceil(content.length / 4),
        content,
      });
    } catch (error) {
      showError(`Failed to add to context: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [activeSessionId, createContextCard, showError]);

  const handleSend = useCallback(async () => {
    if (!input.trim() || isLoadingMessages) {
      return;
    }
    if (!selectedRepository) {
      showError('Select a repository first.');
      return;
    }
    if (!activeSessionId || sessionStatus !== 'ready') {
      if (sessionStatus === 'creating_session' || sessionStatus === 'awaiting_session') {
        showError('Session is still being prepared. Please wait a moment and retry.');
      } else {
        showError('No active chat session available. Please re-select the repository.');
      }
      return;
    }

    const currentInput = input;
    setInput('');

    try {
      const response = await sendChatMessage(
        currentInput,
        selectedRepository
      );
      console.log('[Chat] Message sent successfully:', response.message_id);
    } catch (error) {
      console.error('[Chat] Message sending failed:', error);
      showError(error instanceof Error ? error.message : 'Failed to send message. Please try again.');
      setInput(currentInput);
    }
  }, [input, isLoadingMessages, selectedRepository, activeSessionId, sessionStatus, sendChatMessage, showError]);

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleCreateGitHubIssue = useCallback(async (action?: ChatAction) => {
    if (isCreatingIssue || !selectedRepository) {
      return;
    }

    setIsCreatingIssue(true);

    try {
      // Filter out system messages and convert to ChatContextMessage format
      const conversationMessages: ChatContextMessage[] = messages
        .filter(msg => msg.id !== '1' && msg.id !== '2')
        .map(msg => ({
          id: msg.id,
          content: msg.content,
          isCode: false, // Default to false for chat messages
          timestamp: msg.timestamp.toISOString()
        }));

      console.log('[Chat] Prepared conversation messages:', conversationMessages);

      // Prepare the request using the proper API method
      const fallbackTitle = `Issue from Chat Session - ${selectedRepository.repository.name}`;
      const descriptionParts = [
        action?.issue_description,
        action?.labels && action.labels.length > 0 ? `Suggested labels: ${action.labels.join(', ')}` : null
      ].filter(Boolean) as string[];
      const requestDescription = descriptionParts.length > 0
        ? descriptionParts.join('\n\n')
        : 'This issue was generated from a chat conversation.';

      const request: CreateIssueWithContextRequest = {
        title: action?.issue_title || fallbackTitle,
        description: requestDescription,
        chat_messages: conversationMessages,
        repository_info: {
          owner: selectedRepository.repository.full_name.split('/')[0],
          name: selectedRepository.repository.full_name.split('/')[1],
          branch: selectedRepository.branch
        },
        priority: 'medium'
      };

      // Use the unified sessionStore method for creating issues with context
      const response = await createIssueWithContext(request);

      if (response.success) {
        const issuePreview: IssuePreviewData = {
          ...response.github_preview,
          userIssue: response.user_issue as UserIssueResponse,
          conversationContext: conversationMessages,
          canCreateGitHubIssue: true,
          repositoryInfo: request.repository_info
        };

        // Show the preview modal
        setIssuePreviewModal({
          isOpen: true,
          data: issuePreview,
        });
      }

    } catch (error) {
      console.error('[Chat] Issue creation failed:', error);
      const errorText = `Failed to create GitHub issue: ${error instanceof Error ? error.message : 'Unknown error'}`;
      showError(errorText);
    } finally {
      setIsCreatingIssue(false);
    }
  }, [isCreatingIssue, selectedRepository, messages, showError, createIssueWithContext]);

  const handleConfirmCreateIssue = useCallback(async () => {
    if (!issuePreviewModal.data || !issuePreviewModal.data.userIssue) {
      return;
    }

    try {
      // Call the create GitHub issue API with proper parameters
      if (issuePreviewModal.data.userIssue?.issue_id) {
        const result = await createGitHubIssueFromUserIssue(issuePreviewModal.data.userIssue.issue_id);

        if (result?.success && result?.github_url) {
          console.log('[Chat] GitHub issue created successfully:', result.github_url);
          setIssuePreviewModal({
            isOpen: false,
            data: null,
          });
          if (result.execution_started) {
            setActiveTab('ideas');
            if (activeSessionId) {
              void syncRuntimeState(activeSessionId).catch((runtimeError) => {
                console.warn('[Chat] Failed to refresh runtime state after execution auto-start:', runtimeError);
              });
              void loadMessages(activeSessionId).catch((refreshError) => {
                console.warn('[Chat] Failed to refresh messages after execution auto-start:', refreshError);
              });
            }
          }
          showError(result.message || `GitHub issue created successfully: ${result.github_url}`);
        } else {
          showError(result?.message || 'Failed to create GitHub issue');
        }
      }
    } catch (error) {
      console.error('[Chat] Failed to create GitHub issue:', error);
      showError(`Failed to create GitHub issue: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [
    activeSessionId,
    issuePreviewModal.data,
    showError,
    createGitHubIssueFromUserIssue,
    loadMessages,
    setActiveTab,
    syncRuntimeState,
  ]);

  const handleRegenerateIssue = useCallback(async () => {
    // Close the preview and regenerate
    setIssuePreviewModal({
      isOpen: false,
      data: null,
    });
    // Trigger the create issue process again
    await handleCreateGitHubIssue();
  }, [handleCreateGitHubIssue]);

  const handleSolveIssue = useCallback(async (issueId: string) => {
    if (!selectedRepository || !issuePreviewModal.data || !activeSessionId) {
      showError('No repository or issue selected for solving');
      return;
    }

    const shouldMarkProvisioning =
      runtimeStatus === 'not_provisioned'
      || runtimeStatus === 'failed'
      || runtimeStatus === 'terminated'
      || runtimeStatus === 'stopped';

    try {
      console.log('[Chat] Starting solver for issue:', issueId);

      if (shouldMarkProvisioning) {
        setRuntimeState(null, 'provisioning', null);
      }

      // Close the preview modal
      setIssuePreviewModal({
        isOpen: false,
        data: null,
      });

      const executionObjective = buildExecutionObjective({
        body: issuePreviewModal.data.body,
        branch: selectedRepository.branch || 'main',
        number: issueId,
        repository: selectedRepository.repository.full_name,
        title: issuePreviewModal.data.title,
      });

      const response = await fetch(buildApiUrl(API.SESSIONS.EXECUTION, { sessionId: activeSessionId }), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(sessionToken ? { Authorization: `Bearer ${sessionToken}` } : {}),
        },
        body: JSON.stringify({
          objective: executionObjective,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        const errorMessage =
          typeof errorData?.detail === 'object' && errorData.detail !== null
            ? errorData.detail.message || errorData.detail.detail || response.statusText
            : errorData?.detail || errorData?.message || response.statusText;
        throw new Error(`Execution request failed: ${errorMessage}`);
      }

      const result = await response.json();
      console.log('[Chat] Execution started successfully:', result);

      void syncRuntimeState(activeSessionId).catch((runtimeError) => {
        console.warn('[Chat] Failed to refresh runtime state after solver start:', runtimeError);
      });

      // Best-effort refresh so solver status updates can surface in chat history.
      if (activeSessionId) {
        void loadMessages(activeSessionId).catch((refreshError) => {
          console.warn('[Chat] Failed to refresh messages after solver start:', refreshError);
        });
      }

      // Show success message
      showError(`Execution started. ID: ${result.execution_id}. Watch the chat for mode updates.`);

    } catch (error) {
      void syncRuntimeState(activeSessionId).catch((runtimeError) => {
        console.warn('[Chat] Failed to refresh runtime state after solver error:', runtimeError);
      });
      console.error('[Chat] Failed to start execution:', error);
      showError(`Failed to start execution: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [
    selectedRepository,
    activeSessionId,
    issuePreviewModal.data,
    sessionToken,
    showError,
    loadMessages,
    runtimeStatus,
    setRuntimeState,
    syncRuntimeState,
  ]);



  return (
    <div className="h-full flex flex-col bg-bg terminal-noise">
      <div className="border-b border-border/70 bg-[linear-gradient(115deg,rgba(245,158,11,0.08)_0%,rgba(34,211,238,0.03)_40%,rgba(17,17,19,0.92)_100%)] px-4 py-4">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div>
            <p className="text-[11px] uppercase tracking-[0.18em] text-cyan font-mono mb-1">Conversation</p>
            <h2 className="text-base font-mono font-semibold text-fg">Workspace Chat</h2>
            <p className="text-xs text-fg-secondary font-mono mt-1 truncate">
              {selectedRepository
                ? `${selectedRepository.repository.full_name}@${selectedRepository.branch}`
                : 'No repository selected'}
            </p>
          </div>
          <div className="flex items-center gap-2 text-xs font-mono">
            <span className="px-2.5 py-1 rounded-md bg-bg-tertiary border border-border text-fg-secondary">
              {messages.length} messages
            </span>
            <span className="px-2.5 py-1 rounded-md bg-bg-tertiary border border-border text-fg-secondary">
              {contextCards.length} context
            </span>
            <span
              className={`px-2.5 py-1 rounded-md border ${
                isSessionReady
                  ? 'bg-success/10 text-success border-success/30'
                  : 'bg-cyan/10 text-cyan border-cyan/30'
              }`}
            >
              {isSessionReady ? 'Session Ready' : 'Session Syncing'}
            </span>
          </div>
        </div>
      </div>

      {!selectedRepository && (
        <div className="bg-amber/10 border border-amber/30 rounded-lg p-4 m-4 animate-fade-in">
          <div className="flex items-center gap-2 mb-2">
            <span className="w-2 h-2 rounded-full bg-amber animate-pulse" style={{ boxShadow: '0 0 8px rgba(245, 158, 11, 0.5)' }} />
            <span className="text-amber font-mono font-medium text-sm">No Active Repository</span>
          </div>
          <p className="text-amber/80 text-sm font-mono">
            Select a repository from the picker to initialize a chat session.
          </p>
        </div>
      )}

      {selectedRepository && (sessionStatus === 'awaiting_session' || sessionStatus === 'creating_session') && (
        <div className="bg-cyan/10 border border-cyan/30 rounded-lg p-4 m-4 animate-fade-in">
          <div className="flex items-center gap-2 mb-2">
            <span className="w-2 h-2 rounded-full bg-cyan animate-pulse" />
            <span className="text-cyan font-mono font-medium text-sm">Preparing Session</span>
          </div>
          <p className="text-cyan/80 text-sm font-mono">
            Repository selected. Creating your chat session now...
          </p>
        </div>
      )}

      {selectedRepository && sessionStatus === 'error' && (
        <div className="bg-error/10 border border-error/30 rounded-lg p-4 m-4 animate-fade-in">
          <div className="flex items-center gap-2 mb-2">
            <span className="w-2 h-2 rounded-full bg-error" />
            <span className="text-error font-mono font-medium text-sm">Session Error</span>
          </div>
          <p className="text-error/90 text-sm font-mono">
            {sessionError || messageError || 'A session error occurred. Re-select the repository to create a new session.'}
          </p>
        </div>
      )}

      {isExploringCodebase && (
        <div className="bg-cyan/10 border border-cyan/30 rounded-lg px-4 py-3 mx-4 mt-4 animate-fade-in">
          <div className="flex items-center gap-3">
            <span className="w-2 h-2 rounded-full bg-cyan animate-pulse" />
            <span className="text-cyan font-mono text-sm">
              {explorationDetail || 'Exploring codebase...'}
            </span>
          </div>
        </div>
      )}

      {/* Messages Container */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {selectedRepository && isSessionReady && messages.length === 0 && !isSending && (
          <div className="h-full min-h-[220px] flex items-center justify-center">
            <div className="max-w-xl w-full bg-bg-secondary border border-border rounded-xl p-6 text-center">
              <p className="text-fg font-mono text-sm mb-2">Start a conversation with your repository context</p>
              <p className="text-muted font-mono text-xs">
                Ask for bug analysis, implementation plans, or issue generation. Responses appear here instantly.
              </p>
            </div>
          </div>
        )}

        {messages.map((message, index) => {
          const parsedActions = extractButtonActions(message.content);
          const cleanedContent = stripButtonActions(message.content);
          const messageActions = message.actions && message.actions.length > 0
            ? message.actions
            : parsedActions;
          const actionsToRender = message.role === 'assistant' && messageActions.length === 0 && shouldShowDefaultActions(cleanedContent)
            ? defaultIssueActions
            : messageActions;

          return (
          <div
            key={message.id}
            className={`flex ${message.role === 'assistant' ? 'justify-start' : 'justify-end'} animate-fade-in`}
            style={{ animationDelay: `${index * 50}ms` }}
            onMouseEnter={() => setHoveredMessage(message.id)}
            onMouseLeave={() => setHoveredMessage(null)}
          >
            <div
              className={`max-w-[70%] rounded-xl p-4 transition-all duration-200 ${
                message.role === 'assistant'
                  ? 'bg-bg-secondary border border-border text-fg hover:border-border-accent'
                  : 'bg-amber/10 border border-amber/30 text-fg'
              }`}
            >
              <p className="text-[11px] uppercase tracking-wider font-mono text-fg-secondary mb-2">
                {message.role === 'assistant' ? 'Assistant' : message.role === 'user' ? 'You' : 'System'}
              </p>
              <div className="whitespace-pre-wrap font-mono text-sm leading-relaxed">{cleanedContent}</div>
              {message.role === 'assistant' && actionsToRender.length > 0 && (
                <div className="mt-3 pt-3 border-t border-border/50 flex flex-wrap gap-2">
                  {actionsToRender.map((action) => (
                    <button
                      key={`${message.id}-${action.action_type}-${action.label}-${action.issue_title || ''}`}
                      onClick={() => handleCreateGitHubIssue(action)}
                      disabled={isCreatingIssue || !selectedRepository}
                      className="text-xs font-mono bg-bg-tertiary hover:bg-border/50 px-3 py-1.5 rounded-lg text-fg-secondary hover:text-fg transition-all duration-200 border border-border disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {action.label}
                    </button>
                  ))}
                </div>
              )}
              {hoveredMessage === message.id && message.id !== '1' && message.id !== '2' && (
                <div className="mt-3 pt-3 border-t border-border/50">
                  <button
                    onClick={() => handleAddToContext(cleanedContent)}
                    className="text-xs font-mono bg-bg-tertiary hover:bg-border/50 px-3 py-1.5 rounded-lg text-muted hover:text-fg transition-all duration-200 border border-border"
                  >
                    + Add to Context
                  </button>
                </div>
              )}
            </div>
          </div>
          );
        })}

        {isSending && (
          <div className="flex justify-start animate-fade-in">
            <div className="bg-bg-secondary border border-border text-fg rounded-xl p-4">
              <div className="flex items-center gap-3">
                <div className="flex gap-1">
                  <span className="w-2 h-2 rounded-full bg-amber animate-pulse" style={{ animationDelay: '0ms' }} />
                  <span className="w-2 h-2 rounded-full bg-amber animate-pulse" style={{ animationDelay: '150ms' }} />
                  <span className="w-2 h-2 rounded-full bg-amber animate-pulse" style={{ animationDelay: '300ms' }} />
                </div>
                <span className="font-mono text-sm text-muted">Daifu is thinking...</span>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Input Area */}
      <div className="border-t border-border p-4 bg-bg-secondary">
        <div className="flex gap-3">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={
              !selectedRepository
                ? 'Select a repository to start chatting...'
                : !isSessionReady
                  ? 'Preparing session...'
                  : 'Type your message...'
            }
            disabled={!selectedRepository || !isSessionReady || isSending}
            className="flex-1 bg-bg-tertiary border border-border rounded-lg px-4 py-3 text-fg placeholder:text-muted font-mono text-sm focus:outline-none focus:border-amber/50 focus:ring-2 focus:ring-amber/10 disabled:opacity-50 transition-all duration-200"
          />
          <button
            onClick={handleSend}
            disabled={!input.trim() || isSending || !selectedRepository || !isSessionReady}
            className="bg-amber hover:bg-amber/90 disabled:bg-bg-tertiary disabled:border-border disabled:cursor-not-allowed text-bg-primary disabled:text-muted px-5 py-3 rounded-lg flex items-center gap-2 font-mono text-sm font-semibold transition-all duration-200 border border-amber disabled:border-border glow-amber disabled:shadow-none"
          >
            {isSending ? (
              <div className="animate-spin rounded-full h-4 w-4 border-2 border-bg-primary/20 border-t-bg-primary" />
            ) : (
              <Send size={16} />
            )}
            {isSending ? 'Sending' : 'Send'}
          </button>
          <button
            onClick={() => {
              void handleCreateGitHubIssue();
            }}
            disabled={isCreatingIssue || userMessageCount < 1 || !selectedRepository}
            className="bg-success hover:bg-success/90 disabled:bg-bg-tertiary disabled:border-border disabled:cursor-not-allowed text-bg-primary disabled:text-muted px-5 py-3 rounded-lg flex items-center gap-2 font-mono text-sm font-semibold transition-all duration-200 border border-success disabled:border-border glow-emerald disabled:shadow-none"
            title={!selectedRepository ? 'Select a repository first' : userMessageCount < 1 ? 'Send at least one message' : 'Create GitHub issue from conversation'}
          >
            {isCreatingIssue ? (
              <div className="animate-spin rounded-full h-4 w-4 border-2 border-bg-primary/20 border-t-bg-primary" />
            ) : (
              <Plus size={16} />
            )}
            {isCreatingIssue ? 'Creating' : 'Create Issue'}
          </button>
        </div>
      </div>

      {/* Issue Preview Modal */}
      {issuePreviewModal.isOpen && issuePreviewModal.data && (
        <IssuePreviewModal
          issuePreview={issuePreviewModal.data}
          onClose={() => {
            setIssuePreviewModal({
              isOpen: false,
              data: null,
            });
          }}
          onCreateIssue={handleConfirmCreateIssue}
          onRegenerateIssue={handleRegenerateIssue}
          onSolveIssue={handleSolveIssue}
          isCreating={isCreatingIssue}
        />
      )}
    </div>
  );
};

// Duplicate IssuePreviewModal component removed - using the one defined at the top
