import React, { useState, useCallback, useMemo } from 'react';
import { Send, Plus } from 'lucide-react';
import { Message } from '../types';
import type {
  ChatContextMessage,
  FileContextItem,
  CreateIssueWithContextRequest,
  GitHubIssuePreview,
  UserIssueResponse
} from '../types/sessionTypes';
import { useQueryClient } from '@tanstack/react-query';
import {
  useChatMessages,
  useContextCards,
  useFileDependencies,
  useAddContextCard,
  useCreateIssueWithContext,
  useCreateGitHubIssueFromUserIssue
} from '../hooks/useSessionQueries';
import { useSessionManagement } from '../hooks/useSessionManagement';
import { useRepository } from '../hooks/useRepository';
import { useSessionStore } from '../stores/sessionStore';
import { API, buildApiUrl } from '../config/api';

// Types are now imported from '../types'

// Define missing types
interface ChatProps {
  onShowError?: (message: string) => void;
}

interface IssuePreviewModalProps {
  issuePreview: IssuePreviewData;
  onClose: () => void;
  onCreateIssue: () => void;
  onRegenerateIssue: () => void;
  onSolveIssue: (issueId: number) => void;
  isCreating: boolean;
}

// Define IssuePreviewData interface that extends GitHubIssuePreview
interface IssuePreviewData extends GitHubIssuePreview {
  userIssue?: UserIssueResponse;
  conversationContext: ChatContextMessage[];
  fileContext: FileContextItem[];
  canCreateGitHubIssue: boolean;
  repositoryInfo?: {
    owner: string;
    name: string;
    branch?: string;
  };
}

const IssuePreviewModal: React.FC<IssuePreviewModalProps> = ({
  issuePreview,
  onClose,
  onCreateIssue,
  onRegenerateIssue,
  onSolveIssue,
  isCreating
}) => {
  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-zinc-900 rounded-lg max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6 border-b border-zinc-700">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-semibold text-white">GitHub Issue Preview</h2>
            <button
              onClick={onClose}
              className="text-zinc-400 hover:text-white text-2xl"
            >
              ×
            </button>
          </div>
        </div>

        <div className="p-6 space-y-6">
          {/* Issue Title */}
          <div>
            <label className="block text-sm font-medium text-zinc-300 mb-2">Title</label>
            <div className="bg-zinc-800 rounded p-3 text-white">{issuePreview.title}</div>
          </div>

          {/* Issue Body */}
          <div>
            <label className="block text-sm font-medium text-zinc-300 mb-2">Description</label>
            <div className="bg-zinc-800 rounded p-3 text-white whitespace-pre-wrap max-h-96 overflow-y-auto">
              {issuePreview.body}
            </div>
          </div>

          {/* Labels */}
          <div>
            <label className="block text-sm font-medium text-zinc-300 mb-2">Labels</label>
            <div className="flex flex-wrap gap-2">
              {issuePreview.labels?.map((label, index) => (
                <span
                  key={index}
                  className="bg-blue-600 text-white px-3 py-1 rounded-full text-sm"
                >
                  {label}
                </span>
              ))}
            </div>
          </div>

          {/* Repository Info */}
          <div>
            <label className="block text-sm font-medium text-zinc-300 mb-2">Repository</label>
            <div className="bg-zinc-800 rounded p-3 text-zinc-300">
              {issuePreview.repositoryInfo?.owner}/{issuePreview.repositoryInfo?.name}
              {issuePreview.repositoryInfo?.branch && ` (${issuePreview.repositoryInfo.branch})`}
            </div>
          </div>

          {/* Metadata */}
          <div>
            <label className="block text-sm font-medium text-zinc-300 mb-2">Metadata</label>
            <div className="bg-zinc-800 rounded p-3 text-zinc-400 text-sm">
              <div>Generated by LLM: {issuePreview.metadata?.generated_by_llm ? 'Yes' : 'No'}</div>
              <div>Messages Count: {issuePreview.metadata?.chat_messages_count || 'N/A'}</div>
              <div>Files Count: {issuePreview.metadata?.file_context_count || 'N/A'}</div>
              <div>Tokens Used: {issuePreview.metadata?.total_tokens || issuePreview.metadata?.tokens_used || 'N/A'}</div>
              <div>LLM Model: {issuePreview.metadata?.llm_model || 'openrouter/sonoma-sky-alpha'}</div>
              <div>Generation Method: {issuePreview.metadata?.generation_method || 'llm'}</div>
              {issuePreview.metadata?.processing_time && (
                <div>Processing Time: {issuePreview.metadata.processing_time.toFixed(2)}s</div>
              )}
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="p-6 border-t border-zinc-700 flex gap-3 justify-end">
          <button
            onClick={onRegenerateIssue}
            disabled={isCreating}
            className="px-4 py-2 bg-zinc-700 hover:bg-zinc-600 disabled:bg-zinc-800 text-white rounded disabled:cursor-not-allowed"
          >
            Regenerate Issue
          </button>
          <button
            onClick={onCreateIssue}
            disabled={isCreating}
            className="px-4 py-2 bg-green-600 hover:bg-green-700 disabled:bg-green-800 text-white rounded disabled:cursor-not-allowed flex items-center gap-2"
          >
            {isCreating && <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />}
            {isCreating ? 'Creating...' : 'Create GitHub Issue'}
          </button>
          <button
            onClick={() => {
              // Handle solve issue functionality
              if (issuePreview.userIssue?.id) {
                onSolveIssue(issuePreview.userIssue.id);
              }
            }}
            disabled={isCreating}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-800 text-white rounded disabled:cursor-not-allowed flex items-center gap-2"
          >
            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
            Solve Issue
          </button>
        </div>
      </div>
    </div>
  );
};

// ChatWithPreview component removed - functionality integrated into main Chat component

export const Chat: React.FC<ChatProps> = ({
  onShowError
}) => {
  // Session management hook for state management
  const { activeSessionId } = useSessionManagement();
  const { selectedRepository } = useRepository();

  const queryClient = useQueryClient();
  const { sendChatMessage, extractFileDependenciesForSession } = useSessionStore();

  // State for issue preview modal
  const [showIssuePreview, setShowIssuePreview] = useState(false);
  const [currentIssuePreview, setCurrentIssuePreview] = useState<IssuePreviewData | null>(null);

  // Use the correct hooks from useSessionQueries
  const { data: chatMessages = [] } = useChatMessages(activeSessionId || '');
  const { data: contextCards = [] } = useContextCards(activeSessionId || '');
  const { data: fileContext = [] } = useFileDependencies(activeSessionId || '');

  // Convert API messages to Message format for display
  const messages: Message[] = chatMessages.map((msg) => ({
    id: msg.message_id,
    content: msg.message_text,
    timestamp: new Date(msg.created_at),
    sessionId: activeSessionId || 'default',
  }));

  // Simplified messages state without session management
  const [input, setInput] = useState('');
  const [hoveredMessage, setHoveredMessage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isCreatingIssue, setIsCreatingIssue] = useState(false);
  const [isExtractingFiles, setIsExtractingFiles] = useState(false);

  // Count user messages (messages that are not the initial system messages)
  const userMessageCount = messages.filter(msg =>
    msg.id !== '1' && msg.id !== '2'
  ).length;

  // Get relevant files based on current conversation context
  const relevantFiles = useMemo(() => {
    if (!fileContext || fileContext.length === 0) return [];
    
    // Simple relevance scoring based on file type and recent messages
    const recentMessages = messages.slice(-3); // Last 3 messages
    const messageText = recentMessages.map(m => m.content).join(' ').toLowerCase();
    
    return fileContext
      .filter((file) => {
        // Prioritize files that might be relevant to the conversation
        const fileName = (file.name || file.file_name || '').toLowerCase();
        const filePath = (file.path || file.file_path || '').toLowerCase();

        // Check if file name or path contains keywords from recent messages
        const keywords = messageText.split(' ').filter(word => word.length > 3);
        return keywords.some(keyword =>
          fileName.includes(keyword) || filePath.includes(keyword)
        );
      })
      .slice(0, 3); // Show top 3 relevant files
  }, [fileContext, messages]);

  const showError = useCallback((message: string) => {
    console.error('[Chat] Error occurred:', message);
    if (onShowError) {
      onShowError(message);
    } else {
      console.error('Chat Error:', message);
    }
  }, [onShowError]);

  // Session creation is now handled by useSessionManagement hook
  // This component no longer needs to create sessions directly

  const addContextCardMutation = useAddContextCard();
  const createIssueMutation = useCreateIssueWithContext();
  const createGitHubIssueMutation = useCreateGitHubIssueFromUserIssue();

  const handleAddToContext = useCallback(async (content: string) => {
    if (!activeSessionId) {
      showError('No active session to add context to');
      return;
    }

    addContextCardMutation.mutate({
      sessionId: activeSessionId,
      card: {
        title: 'Chat Message',
        description: content.length > 100 ? content.substring(0, 100) + '...' : content,
        source: 'chat',
        tokens: Math.ceil(content.length / 4),
        content,
      },
    }, {
      onError: () => showError('Failed to add to context'),
    });
  }, [activeSessionId, addContextCardMutation, showError]);

  const handleSend = useCallback(async () => {
      if (!input.trim() || isLoading || !activeSessionId) {
          return;
      }
      
      const currentInput = input;
      setInput('');
      setIsLoading(true);
  
      try {
          // Use unified sessionStore method for sending chat messages
          const response = await sendChatMessage(
              currentInput,
              contextCards.map((card) => card.id),
              selectedRepository || undefined
          );

          if (response) {
              console.log('[Chat] Message sent successfully:', response.message_id);

              // Invalidate and refetch the messages to show the updated conversation
              await queryClient.invalidateQueries({
                queryKey: ['messages', activeSessionId]
              });
          }
          
      } catch (error) {
          console.error('[Chat] Message sending failed:', error);
          showError('Failed to send message. Please try again.');
      } finally {
          setIsLoading(false);
      }
  }, [input, isLoading, activeSessionId, contextCards, selectedRepository, sendChatMessage, showError, queryClient]);

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleCreateGitHubIssue = useCallback(async () => {
    if (isCreatingIssue || !selectedRepository) {
      return;
    }

    setIsCreatingIssue(true);

    try {
      // Filter out system messages and convert to ChatContextMessage format
      const conversationMessages: ChatContextMessage[] = messages
        .filter(msg => msg.id !== '1' && msg.id !== '2')
        .map(msg => ({
          id: msg.id,
          content: msg.content,
          isCode: false, // Default to false for chat messages
          timestamp: msg.timestamp.toISOString()
        }));

      console.log('[Chat] Prepared conversation messages:', conversationMessages);

      // Convert file context to FileContextItem format
      const fileContextItems: FileContextItem[] = fileContext.map((file) => ({
        id: file.id,
        name: file.name || file.file_name || '',
        type: file.type || 'INTERNAL',
        tokens: file.tokens,
        category: file.category || '',
        path: file.path || file.file_path || ''
      }));

      // Prepare the request using the proper API method
      const request: CreateIssueWithContextRequest = {
        title: `Issue from Chat Session - ${selectedRepository.repository.name}`,
        description: 'This issue was generated from a chat conversation with file dependency context.',
        chat_messages: conversationMessages,
        file_context: fileContextItems,
        repository_info: {
          owner: selectedRepository.repository.full_name.split('/')[0],
          name: selectedRepository.repository.full_name.split('/')[1],
          branch: selectedRepository.branch
        },
        priority: 'medium'
      };

      // Use the unified sessionStore method for creating issues with context
      const response = await createIssueMutation.mutateAsync(request);

      if (response && response.success) {
        const issuePreview: IssuePreviewData = {
          ...response.github_preview,
          userIssue: response.user_issue as UserIssueResponse,
          conversationContext: conversationMessages,
          fileContext: fileContextItems,
          canCreateGitHubIssue: true,
          repositoryInfo: request.repository_info
        };

        // Show the preview modal
        setCurrentIssuePreview(issuePreview);
        setShowIssuePreview(true);
      }

    } catch (error) {
      console.error('[Chat] Issue creation failed:', error);
      const errorText = `Failed to create GitHub issue: ${error instanceof Error ? error.message : 'Unknown error'}`;
      showError(errorText);
    } finally {
      setIsCreatingIssue(false);
    }
  }, [isCreatingIssue, selectedRepository, messages, fileContext, showError, createIssueMutation]);

  const handleConfirmCreateIssue = useCallback(async () => {
    if (!currentIssuePreview || !currentIssuePreview.userIssue) {
      return;
    }

    try {
      // Call the create GitHub issue API with proper parameters
      if (currentIssuePreview.userIssue?.id) {
        const result = await createGitHubIssueMutation.mutateAsync(currentIssuePreview.userIssue.id.toString());
        if (result?.success) {
          console.log('[Chat] GitHub issue created successfully');
          setShowIssuePreview(false);
          setCurrentIssuePreview(null);
        }
      }
    } catch (error) {
      console.error('[Chat] Failed to create GitHub issue:', error);
      showError('Failed to create GitHub issue');
    }
  }, [currentIssuePreview, showError, createGitHubIssueMutation]);

  const handleRegenerateIssue = useCallback(async () => {
    // Close the preview and regenerate
    setShowIssuePreview(false);
    setCurrentIssuePreview(null);
    // Trigger the create issue process again
    await handleCreateGitHubIssue();
  }, [handleCreateGitHubIssue]);

  const handleSolveIssue = useCallback(async (issueId: number) => {
    if (!selectedRepository) {
      showError('No repository selected for solving issue');
      return;
    }

    try {
      console.log('[Chat] Starting solver for issue:', issueId);

      // Close the preview modal
      setShowIssuePreview(false);
      setCurrentIssuePreview(null);

      // Call the solver endpoint using unified API
      const response = await fetch(buildApiUrl(API.SESSIONS.SOLVER.START, { sessionId: activeSessionId || '' }), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('session_token') || ''}`,
        },
        body: JSON.stringify({
          issue_id: issueId,
          repo_url: `https://github.com/${selectedRepository.repository.full_name}`,
          branch: selectedRepository.branch || 'main'
        }),
      });

      if (!response.ok) {
        throw new Error(`Solver request failed: ${response.statusText}`);
      }

      const result = await response.json();
      console.log('[Chat] Solver started successfully:', result);

      // Show success message
      showError('AI Solver started successfully! Check the solve session status for progress.');

    } catch (error) {
      console.error('[Chat] Failed to start solver:', error);
      showError(`Failed to start solver: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [selectedRepository, activeSessionId, showError]);



  return (
    <div className="h-full flex flex-col">
      {/* Session Status Indicator */}
      {!selectedRepository && (
        <div className="bg-yellow-600/20 border border-yellow-600/30 rounded-lg p-4 mb-4">
          <div className="text-yellow-400 font-medium mb-2">No Active Repository</div>
          <div className="text-yellow-300 text-sm mb-3">
            Please select a repository to start a new session and begin chatting with Daifu.
          </div>
          <button
            onClick={() => {
              // Trigger repository selection manually
              window.location.reload();
            }}
            className="bg-yellow-600 hover:bg-yellow-700 text-white px-3 py-1 rounded text-sm"
          >
            Select Repository
          </button>
        </div>
      )}
      
      {/* File Context Display */}
      {relevantFiles.length > 0 && (
        <div className="bg-zinc-900/50 border border-zinc-700 rounded-lg p-3 mx-4 mb-4">
          <div className="text-sm text-zinc-400 mb-2">📁 Relevant Files</div>
          <div className="space-y-1">
            {relevantFiles.map((file) => (
              <div key={file.id} className="flex items-center justify-between text-xs">
                <span className="text-zinc-300 truncate flex-1">
                  {file.name || file.file_name}
                </span>
                <div className="flex items-center gap-2">
                  <span className="text-zinc-500">{file.tokens} tokens</span>
                  <button
                    onClick={() => handleAddToContext(`File: ${file.name || file.file_name} (${file.path || file.file_path})`)}
                    className="text-blue-400 hover:text-blue-300 text-xs"
                    title="Add file to context"
                  >
                    Add
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* File Dependencies Extraction Prompt */}
      {selectedRepository && fileContext.length === 0 && (
        <div className="bg-blue-600/20 border border-blue-600/30 rounded-lg p-4 mx-4 mb-4">
          <div className="text-blue-400 font-medium mb-2">📁 No File Dependencies Found</div>
          <div className="text-blue-300 text-sm mb-3">
            Extract file dependencies from the repository to enable file context in your conversations.
          </div>
          <button
            onClick={async () => {
              if (!selectedRepository || isExtractingFiles) return;
              setIsExtractingFiles(true);
              try {
                const repoUrl = `https://github.com/${selectedRepository.repository.full_name}`;
                await extractFileDependenciesForSession(activeSessionId || '', repoUrl);
                // Refetch file dependencies after extraction
                await queryClient.invalidateQueries({ 
                  queryKey: ['file-deps', activeSessionId] 
                });
              } catch (error) {
                console.error('[Chat] Error extracting file dependencies:', error);
                showError('Failed to extract file dependencies. Please try again.');
              } finally {
                setIsExtractingFiles(false);
              }
            }}
            disabled={isExtractingFiles}
            className="bg-blue-600 hover:bg-blue-700 disabled:bg-blue-800 disabled:cursor-not-allowed text-white px-3 py-1 rounded text-sm flex items-center gap-2"
          >
            {isExtractingFiles ? (
              <>
                <div className="animate-spin rounded-full h-3 w-3 border-b-2 border-white" />
                Extracting...
              </>
            ) : (
              'Extract File Dependencies'
            )}
          </button>
        </div>
      )}

      {/* Messages Container */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((message) => (
          <div
            key={message.id}
            className={`flex ${message.id === '2' ? 'justify-start' : 'justify-end'}`}
            onMouseEnter={() => setHoveredMessage(message.id)}
            onMouseLeave={() => setHoveredMessage(null)}
          >
            <div
              className={`max-w-[70%] rounded-lg p-3 ${
                message.id === '2'
                  ? 'bg-zinc-800 text-zinc-200'
                  : 'bg-blue-600 text-white'
              }`}
            >
              <div className="whitespace-pre-wrap">{message.content}</div>
              {hoveredMessage === message.id && message.id !== '1' && message.id !== '2' && (
                <div className="mt-2 flex gap-2">
                  <button
                    onClick={() => handleAddToContext(message.content)}
                    className="text-xs bg-zinc-700 hover:bg-zinc-600 px-2 py-1 rounded"
                  >
                    Add to Context
                  </button>
                </div>
              )}
            </div>
          </div>
        ))}
        
        {isLoading && (
          <div className="flex justify-start">
            <div className="bg-zinc-800 text-zinc-200 rounded-lg p-3">
              <div className="flex items-center gap-2">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-zinc-400"></div>
                <span>Daifu is thinking...</span>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Input Area */}
      <div className="border-t border-zinc-700 p-4">
        <div className="flex gap-2">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder={selectedRepository ? "Type your message..." : "Select a repository to start chatting..."}
            disabled={!selectedRepository || isLoading}
            className="flex-1 bg-zinc-800 border border-zinc-600 rounded-lg px-3 py-2 text-white placeholder-zinc-400 focus:outline-none focus:border-blue-500 disabled:opacity-50"
          />
          <button
            onClick={handleSend}
            disabled={!input.trim() || isLoading || !selectedRepository}
            className="bg-blue-600 hover:bg-blue-700 disabled:bg-zinc-600 disabled:cursor-not-allowed text-white px-4 py-2 rounded-lg flex items-center gap-2"
          >
            {isLoading ? (
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
            ) : (
              <Send size={16} />
            )}
            {isLoading ? 'Sending...' : 'Send'}
          </button>
          <button
            onClick={handleCreateGitHubIssue}
            disabled={isCreatingIssue || userMessageCount < 1 || !selectedRepository}
            className="bg-green-600 hover:bg-green-700 disabled:bg-zinc-600 disabled:cursor-not-allowed text-white px-4 py-2 rounded-lg flex items-center gap-2"
            title={!selectedRepository ? 'Select a repository first' : userMessageCount < 1 ? 'Send at least one message' : 'Create GitHub issue from conversation'}
          >
            {isCreatingIssue ? (
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
            ) : (
              <Plus size={16} />
            )}
            {isCreatingIssue ? 'Creating...' : 'Create Issue'}
          </button>
        </div>
      </div>

      {/* Issue Preview Modal */}
      {showIssuePreview && currentIssuePreview && (
        <IssuePreviewModal
          issuePreview={currentIssuePreview}
          onClose={() => {
            setShowIssuePreview(false);
            setCurrentIssuePreview(null);
          }}
          onCreateIssue={handleConfirmCreateIssue}
          onRegenerateIssue={handleRegenerateIssue}
          onSolveIssue={handleSolveIssue}
          isCreating={isCreatingIssue}
        />
      )}
    </div>
  );
};

// Duplicate IssuePreviewModal component removed - using the one defined at the top